### ISSUE TITLE
clarification regarding header elements

### ISSUE THREAD

**Issue by Hithesh2022** [LambdaTest/Lambdatest-GitHub-Octernship#3]
i just wanted to confirm that we have to write script only for  visible nav header ?or should also include  drop down elements when hovered?

**Comment by Hithesh2022** [comment]
hi @SparshKesari just wanted to confirm that we have to write script only for visible nav header ?or should also include drop down elements when hovered?

**Comment by Hithesh2022** [comment]
@SparshKesari  also i am able to collect 100 logs for homepage,platform,pricing,developer,resoufces,login,booknow,signup,enterprice which are in nav so shall can i continue for visulazation step or wait for you to review code?

**Comment by SparshKesari** [comment]
Hey @Hithesh2022,
There will be no code review before and your submission will be reviewed after submission deadline.
